name: 'Greet the calling branch'
description: 'Say welcome'
inputs:
  branch_name:  
    description: 'Branch Name'
    required: true
outputs:
  action_type: 
    description: 'Executed action type'
runs:
  using: 'node16'
  main: 'index.js'