name: Git Action sample for Event Trigger

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  worlflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Event Trigger
