name: 'Greet the calling branch'
description: 'Say welcome'
inputs:
  branch_name:  
    description: 'Branch Name'
    required: true
outputs:
  action_type: 
    description: 'Executed action type'
    value: ${{ steps.setActionType.outputs.action_type }}
runs:
  using: "composite"
  steps:
    - name: Say welcome
      run: echo Welcome ${{ inputs.branch_name }}
      shell: bash
    - id: setActionType  
      run: echo "action_type=Composite" >> $GITHUB_OUTPUT
      shell: bash
      
